kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: aispring
  labels:
    app: redis
data:
  redis.conf: |-
    dir /data
    port 6379
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    # requirepass 123456
    pidfile /data/redis-6379.pid
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: aispring
  name: redis-pv-claim
  labels:
    app: redis
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
