apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: aispring
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 5432
      protocol: TCP
  selector:
    app: postgresql
