apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: aispring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - image: grafana/grafana
          name: grafana
          imagePullPolicy: IfNotPresent
          # env:
          env:
            - name: GF_PATHS_PROVISIONING
              value: /var/lib/grafana/provisioning
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
            # initialDelaySeconds: 30
            # timeoutSeconds: 1
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana/
            - name: config
              mountPath: /etc/grafana/
      initContainers:
        - name: "init-chown-data"
          image: "busybox:latest"
          imagePullPolicy: "IfNotPresent"
          command: ["chown", "-R", "472:472", "/var/lib/grafana/"]
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana/
              subPath: ""
      volumes:
        - name: config
          configMap:
            name: grafana-config
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pv-claim
