apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: aispring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - grafana.aispring.cloud
        - "*.aispring.cloud"
      secretName: aispring-https-certs
  rules:
    - host: grafana.aispring.cloud
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: http
