apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
  namespace: aispring
data:
  redis-host: redis
  redis-port: "6379"
  redis-db: "1"
  postgresql-host: postgresql
  postgresql-port: "5432"
  postgresql-user: gitlab
  postgresql-db: gitlab
  gitlab-host: git.aispring.cloud
  gitlab-root-email: 3377939225@qq.com

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: aispring
  name: gitlab-pv-claim
  labels:
    app: gitlab
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
